# Generated by Django 4.1.6 on 2023-04-30 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
